# Fly.io configuration for the realtime assistant frontend
app = "realtime-assistant-frontend"
primary_region = "iad" # US East (Virginia) - change as needed
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"
  target = "frontend"
  ignorefile = ".dockerignore"

[env]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Update this with your backend URL after deploying backend
  NEXT_PUBLIC_BACKEND_URL = "https://realtime-assistant-backend.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false
    headers = {}

[deploy]
  strategy = "rolling"
  max_unavailable = 0