[build]
  base = "apps/frontend"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=../../ --production=false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/visual"
  to = "https://your-backend-url.com/visual"
  status = 200
  force = true

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200